# Generated by Django 4.1.7 on 2023-04-02 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_model',
            old_name='names',
            new_name='name',
        ),
    ]
