# Generated by Django 4.1.7 on 2023-04-03 05:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_rename_names_post_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
