# Generated by Django 4.1.7 on 2023-04-03 06:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_post_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='image',
        ),
        migrations.AddField(
            model_name='post_model',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='img'),
        ),
    ]
