# Generated by Django 4.1.7 on 2023-04-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_remove_post_model_date_time_post_model_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='likes'),
        ),
    ]
